### ISSUE TITLE
guide how to run the code

### ISSUE THREAD

**Issue by mmitchef** [vonclites/livdet_fusion#1]
Hello, thanks for sharing your code. Do you have any guideline how to run the code? thanks

**Comment by vonclites** [comment]
Hello.
This was my first project, so apologies for the poor documentation. I did not keep track of which version of Tensorflow I used, but I know it uses an older 1.x version of Tensorflow, probably whatever version was the latest ~4-5 years ago. I also use a couple of my own libraries: https://github.com/vonclites/checkmate and https://github.com/vonclites/tftools.

Unfortunately you may have better luck using the code and the paper (https://dl.gi.de/bitstream/handle/20.500.12116/23808/BIOSIG_2018_paper_38.pdf) as a reference for re-implementation using a newer version or framework of your choice.

**Comment by mmitchef** [comment]
@vonclites thanks for responding me and providing these information.
